### ISSUE TITLE
If my ryzen is fine, will the program run forever?

### ISSUE THREAD

**Issue by ameaninglessname** [corngood/kill-ryzen-win#4]

**Comment by corngood** [comment]
Yeah, it'll just keep printing bzip2.c if it's working, but that doesn't prove your ryzen is fine.  I suggest also running the linux gcc test.

Did you have authenticode enabled?  You can check in regedit for `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Safer\CodeIdentifiers\AuthenticodeEnabled`.  If it's not there, or it's set to zero, then the test won't crash (for me at least).
